http:
  protocol: "HTTP"
  host: "0.0.0.0"
  port: "8081"
  
sapi:
  protocol: "HTTP"
  host: "sapi-student-counselling.us-e2.cloudhub.io"
  port: "80"

papi:
  protocol: "HTTP"
  host: "papi-student-counselling.us-e2.cloudhub.io"
  port: "80"
 
mongo:
  username: "MuleIntern2022"
  password: "vLhoBp7TxmW2opuV"
  dbname: "counselling_data"
  college_collection:
    name: "college_details"
    fields: "id,name,criteria,seatsAvailable,seatsDetails,admissionFees"
  student_collection:
    name: "student_details"
    fields: "uid,fname,lname,sex,caste,dob,address,contactDetails,educationDetails"
  enrolment_collection:
    name: "enrolment_details" 
    fields: "student_id,assigned_id,college_details"
  admission_collection:
    name: "admission_details" 
    fields: "student_id,assigned_id,college_details,admissionFees"
  library_collection:
    name: "library_details" 
    fields: "library_id,student_id,assigned_id,college_details"
    
    
    
ping:
  module: "SAPI Student Counselling"
  projectVersion: "2.0.0"
  apiVersion: "2.0.0"
  env: "DEV"
  status: "200"
  message: "Alive"