#%RAML 1.0
title: SAPI Student Counselling

uses:
  commons: /exchange_modules/26105a91-12e5-4470-b3a0-40b228e3e2a0/sc_commonslib/0.0.5/sc_commonslib.raml

/student: 
  is: 
    - commons.client_id_required
    - commons.database_prereq
  get:
    description: Request particular student details by id
    queryParameters:
      id: string
    responses:
      200:
        description: Requested student found successfully
        body:
          application/json:
            type: commons.student_type
            example: !include /examples/StudentExample.json
      404:
        description: Requested student not found
        body:
          application/json:
            type: commons.error_response
            example: {"error_message": "Requested student id not found"}

/college:
  is: 
    - commons.client_id_required
    - commons.database_prereq
  get:
    description: Request particular college details by id
    queryParameters:
      id: string
    responses:
      200:
        description: Requested college found successfully
        body:
          application/json:
            type: commons.college_type           
            example: !include /examples/CollegeExample.json
      404:
        description: Requested College not found
        body:
          application/json:
            type: commons.error_response
            example: {"error_message": "Requested college id not found"}

  patch:
    description: Update particular college availability details 
    body:
      application/json:
        example: !include /examples/CollegeExample.json
    responses:
      200:
        description: College update successful
        body:
          application/json:
            type: commons.success_response
            example: {"success_message": "College update success"}
            
      500:
        description: College update error
        body:
          application/json:
            type: commons.error_response
            example: {"error_message": "College update failure"}

/enrolment:
  is: 
    - commons.client_id_required
    - commons.database_prereq
  get:
    description: Get enrolled student details
    queryParameters:
      id: string
    responses:
      200:
        description: Requested student enrolment details found successfully
        body:
          application/json:
            type: commons.enrolment_type
            example: !include /examples/EnrolledExample.json
      404:
        description: Requested student enrolment details not found
        body:
          application/json:
            type: commons.error_response
            example: {"error_message": "Requested enrolment id not found"}
            
  post:
    description: Enroll particular student to specified college
    body:
      application/json:
        example: !include /examples/EnrolledExample.json
    responses:
      201:
        description: Enrolment successful
        body:
          application/json:
            type: commons.success_response
            example: {"success_message": "Student enrolment successful"}
      500:
        description: Enrolment error
        body:
          application/json:
            type: commons.error_response
            example: {"error_message": "Student enrolment failed"}

/ping:
  get:
    description: Healthcheck endpoint
    responses:
      200:
        description: Healthcheck service online
        body:
          application/json:
            example: !include /examples/HealthcheckExample.json
        
       